# Generated by Django 4.2.11 on 2024-11-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlackListedIPAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
            ],
            options={
                "verbose_name": "Black Listed IP",
                "verbose_name_plural": "Black Listed IPs",
            },
        ),
    ]
