# Generated by Django 4.2.11 on 2024-11-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reciepes",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
